"""add correlation value to webhook model

Revision ID: e95dcecf9c6a
Revises: 0b4c46d1c65c
Create Date: 2025-02-22 08:58:27.022032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95dcecf9c6a'
down_revision: Union[str, None] = '0b4c46d1c65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('correlation_value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhooks', 'correlation_value')
    # ### end Alembic commands ###
